runtime: python
build:
  pythonVersion: 3.11.0

services:
  - type: web
    name: samay-news-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
